name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bundle exec bin/brakeman --no-pager

      - name: Lint code for consistent style
        run: bundle exec bin/rubocop

      - name: precompile assets
        run: bundle exec rails assets:precompile

      - name: Run rspec
        env:
          RAILS_ENV: test
        run: bundle exec rspec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit
